<a href="https://colab.research.google.com/github/wilsonarrubla/Ciclo3/blob/master/Despliegue_Car_Risk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Despliegue: Car Risk**
- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo de predicción

In [ ]:
#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
import pickle
filename = 'modelo-clas-tree-knn-nn.pkl'
modelTree,modelKnn,modelNN,labelencoder,variables,min_max_scaler = pickle.load(open(filename, 'rb')) #read

In [ ]:
#Cargamos los datos futuros

data = pd.read_csv("carRisk-future.csv", sep = ",")
data.head()

   age cartype
0   20   combi
1   18   sport
2   50  family

In [ ]:
#Se realiza la preparación creando dummis

data_preparada=data.copy()
data_preparada = pd.get_dummies(data_preparada, columns=['cartype'], drop_first=False)
data_preparada.head()

   age  cartype_combi  cartype_family  cartype_sport
0   20              1               0              0
1   18              0               0              1
2   50              0               1              0

In [ ]:
#Se adicionan las columnas faltantes en este caso Minivan

data_preparada=data_preparada.reindex(columns=variables,fill_value=0)

data_preparada.head()

   age  cartype_combi  cartype_family  cartype_minivan  cartype_sport
0   20              1               0                0              0
1   18              0               0                0              1
2   50              0               1                0              0

# **Predicción con Tree**

In [ ]:
#Hacemos la predicción con Tree

Y_fut = modelTree.predict(data_preparada)

print(Y_fut)

[0 0 1]

In [ ]:
print (labelencoder.inverse_transform(Y_fut))

['high' 'high' 'low']

In [ ]:
data['Prediccion Tree']=labelencoder.inverse_transform(Y_fut)

data

   age cartype Prediccion Tree
0   20   combi            high
1   18   sport            high
2   50  family             low

# **Prediccion con KNN**

In [ ]:
#Normalización

data_preparada[['age']]= min_max_scaler.transform(data[['age']]) 
data_preparada.head()

      age  cartype_combi  cartype_family  cartype_minivan  cartype_sport
0  0.0625              1               0                0              0
1  0.0000              0               0                0              1
2  1.0000              0               1                0              0

In [ ]:
#Hacemos la predicción con knn

Y_fut = modelKnn.predict(data_preparada)

data['Prediccion Knn']=labelencoder.inverse_transform(Y_fut)

data

   age cartype Prediccion Tree Prediccion Knn
0   20   combi            high           high
1   18   sport            high           high
2   50  family             low            low

# **Neuural Network**

In [ ]:
#Hacemos la predicción con la NN
Y_fut = modelNN.predict(data_preparada)
data['Prediccion NN']=labelencoder.inverse_transform(Y_fut)
data

   age cartype Prediccion Tree Prediccion Knn Prediccion NN
0   20   combi            high           high          high
1   18   sport            high           high          high
2   50  family             low            low           low